# Generated by Django 5.2.2 on 2025-06-06 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('identifiant_compteur', models.IntegerField(max_length=12, primary_key=True, serialize=False)),
                ('numero_compteur', models.IntegerField(max_length=11)),
                ('exploitation', models.CharField(max_length=50)),
                ('reference', models.IntegerField(max_length=13)),
                ('type_client', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('identifiant', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('numero_tel', models.IntegerField()),
                ('mot_de_passe', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tension', models.FloatField()),
                ('courant', models.FloatField()),
                ('puissance', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.compteur')),
            ],
        ),
        migrations.AddField(
            model_name='compteur',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilisateur'),
        ),
    ]
