# Generated by Django 5.2.2 on 2025-06-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_compteur_identifiant_compteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteur',
            name='identifiant_compteur',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='compteur',
            name='numero_compteur',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='compteur',
            name='reference',
            field=models.BigIntegerField(),
        ),
    ]
