# Generated by Django 4.2.18 on 2025-06-12 14:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_compteur_identifiant_compteur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prise',
            fields=[
                ('identifiant', models.BigAutoField(primary_key=True, serialize=False)),
                ('etat', models.BooleanField(default=True)),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.compteur')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueConsommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('conso_totale', models.FloatField()),
                ('conso_journaliere', models.FloatField()),
                ('prise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prise')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SURCONSO', 'Surconsommation'), ('COUPURE', 'Coupure_de_courant')], max_length=40)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('prise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prise')),
            ],
        ),
    ]
