# Generated by Django 4.2.18 on 2025-06-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_prise_historiqueconsommation_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiqueconsommation',
            old_name='conso_totale',
            new_name='conso_heure',
        ),
        migrations.RemoveField(
            model_name='historiqueconsommation',
            name='prise',
        ),
        migrations.AddField(
            model_name='historiqueconsommation',
            name='compteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.compteur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historiqueconsommation',
            name='conso_journaliere',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiqueconsommation',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
