# Generated by Django 5.2.2 on 2025-06-13 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_conso_totale_historiqueconsommation_conso_heure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sender', models.CharField(choices=[('USER', 'Utilisateur'), ('BOT', 'ChatBot')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilisateur')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
